export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  SELECT_PROJECT: '/select-project',
  TESTSUITE: '/project/test-suites',
  TESTSUITE_NEW: '/project/test-suites/new',
  TESTSUITE_DETAIL: '/project/test-suites/:testSuiteId',
  TESTSUITE_DETAIL_EDIT: '/project/test-suites/:testSuiteId/edit',
  TESTCASE: '/project/test-cases',
  TESTCASE_NEW: '/project/test-cases/new',
  TESTCASE_DETAIL: '/project/test-cases/:testCaseId',
  TESTCASE_DETAIL_EDIT: '/project/test-cases/:testCaseId/edit',
  PAGE: '/project/pages',
  PAGE_NEW: '/project/pages/new',
  PAGE_DETAIL: '/project/pages/:pageId',
  PAGE_DETAIL_EDIT: '/project/pages/:pageId/edit',
  PROJECT: '/project',
  ENVIRONMENT: '/project/environments',
  TEST_RESULT: '/project/tests-result',

  HOME: '/',
  NO_AUTHEN: '/403',
  SERVER_ERROR: '/500'
};
